### ISSUE TITLE
User icon is shifted

### ISSUE THREAD

**Issue by Aeris1One** [yunohost-themes/Nature-Mount#1]
![image](https://user-images.githubusercontent.com/29739547/97080128-80fc7200-15f9-11eb-99b1-86ac24bfa52f.png)

**Comment by stilobique** [comment]
Hello, can you specifie your broswer ? I'm used it with firefox, but don't take a time to fix on Chrome or Opera.

**Comment by stilobique** [comment]
Hi @Aeris1One, i'm make a fix with the last commit ; can you try the dev branch ?

**Comment by Aeris1One** [comment]
I was using Chrome when posting this issue, same with Firefox. I'll have a try with dev branch.

**Comment by Aeris1One** [comment]
Solved on dev branch, thanks !
